# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='associated_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dwitterapp.Post'),
            preserve_default=False,
        ),
    ]
