# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0005_auto_20181024_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='associated_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dwitterapp.Post'),
            preserve_default=False,
        ),
    ]
