# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0006_auto_20181024_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwitterapp.Post'),
        ),
    ]
