# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0007_auto_20181024_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
    ]
