# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0008_auto_20181026_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dwitterapp.Post'),
        ),
    ]
