# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0010_auto_20181026_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
